services:
  - type: web
    name: dropout-predictor-backend
    env: python
    buildCommand: pip install -r requirements.txt && python train.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
